name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run tests on macOS
        run: |
          xcodebuild test \
            -scheme KinjoCore-Package \
            -destination 'platform=macOS' \
            -enableCodeCoverage NO

  test-ios:
    name: Test on iOS Simulator
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Run tests on iOS Simulator
        run: |
          # Shutdown all simulators to ensure clean state
          xcrun simctl shutdown all 2>/dev/null || true
          sleep 1
          # Boot simulator
          xcrun simctl boot "iPhone 17" 2>/dev/null || true
          sleep 3
          # Run tests
          xcodebuild test \
            -scheme KinjoCore-Package \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.0' \
            -parallel-testing-enabled NO \
            -enableCodeCoverage NO
          # Shutdown after tests
          xcrun simctl shutdown "iPhone 17" 2>/dev/null || true
